language: csharp
solution: ModernPlayerManager.sln
mono: none

after_success:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL
